import { randomInt } from 'node:crypto';

/**
 * SRS 1.2 — tracking numbers and carriers are generated by this system, never
 * fetched from a real courier API. The carrier names are deliberately fictional
 * so nobody mistakes a simulated shipment for a real one.
 */
const CARRIERS = [
  'BidNest Express',
  'Nest Logistics',
  'Simulated Post'
] as const;

const ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; // no I/O/0/1 — misread easily

export type SimulatedTracking = {
  trackingNumber: string;
  carrier: string;
};

export function generateTracking(now = new Date()): SimulatedTracking {
  const yy = String(now.getFullYear()).slice(-2);
  const mm = String(now.getMonth() + 1).padStart(2, '0');
  const dd = String(now.getDate()).padStart(2, '0');

  let suffix = '';
  for (let i = 0; i < 6; i += 1) {
    suffix += ALPHABET[randomInt(ALPHABET.length)];
  }

  return {
    trackingNumber: `BN${yy}${mm}${dd}${suffix}`,
    carrier: CARRIERS[randomInt(CARRIERS.length)]
  };
}
