// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    // Delegated to the package.json script rather than spelled out here.
    // Prisma runs this string without a shell, so a `&&` in it is never a
    // chain: the whole thing is looked up as one command name, fails, and is
    // reported as success. `pnpm run` is a single command, and the script it
    // reaches does get a shell.
    //
    // The build is not optional: the generated Prisma client imports with
    // `.js` specifiers that only tsc resolves back to its `.ts` sources.
    seed: 'pnpm run seed'
  },
  datasource: {
    url: process.env['DATABASE_URL']
  }
});
